[options]
  colorscheme = "purify"
  background = "dark"
  enable_guicolors = true
  guifont = "FuraCode Nerd Font:h14"
  statusline_separator = "slant"
  statusline_inactive_separator = "bar"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_display_mode = false
  bootstrap_before = "myspacevim#before"
  lint_on_the_fly = true
  filemanager = "nerdtree"
  autocomplete_method = "coc"
  filetree_direction = "right"
  enable_cursorcolumn = true
[[custom_plugins]]
  name = "thosakwe/vim-flutter"
  merged = 0
[[custom_plugins]]
  name = "sodapopcan/vim-twiggy"
  merged = 0
[[custom_plugins]]
  name = "MaethorNaur/purify-vim"
    merged = 0
[[custom_plugins]]
  name = "kristijanhusak/vim-carbon-now-sh"
  merge = 0
[[custom_plugins]]
  name = "HendrikPetertje/vimify"
  merge = 0
[[custom_plugins]]
  name = "vim-scripts/dbext.vim"
  merged = 0
[[custom_plugins]]
  name = "luochen1990/rainbow"
  merge = 0
[[custom_plugins]]
  name = "liquidz/lein-vim"
  merge = 0
[[custom_plugins]]
  name = "ryanoasis/vim-devicons"
  merge = 0
[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0
[[custom_plugins]]
  name = "christianrondeau/vim-base64"
  merge = 0
[[custom_plugins]]
  name = "Shougo/vimproc.vim"
  merge = 0
[[custom_plugins]]
  name = "whiteinge/diffconflicts"
  merge = 0
[[custom_plugins]]
  name = "robertbasic/vim-hugo-helper"
  merge = 0
[[custom_plugins]]
  name = "hashivim/vim-terraform"
  merge = 0
[[custom_plugins]]
  name = "neoclide/coc.nvim"
  merge = 0
[[custom_plugins]]
  name = "neoclide/vim-node-rpc"
  merge = 0
[[custom_plugins]]
  name = "terryma/vim-multiple-cursors"
  merge = 0
[[custom_plugins]]
  name = "tpope/vim-surround"
  merge = 0
[[custom_plugins]]
  name = "roxma/nvim-yarp"
  merge = 0
[[custom_plugins]]
  name = "mattn/emmet-vim"
  merge = 0
[[custom_plugins]]
  name = "roxma/vim-hug-neovim-rpc"
  merge = 0
[[custom_plugins]]
  name = "vim-syntastic/syntastic"
  merged = 0
[[layers]]
  name = "debug"
[[layers]]
  name = "leaderf"
[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "VersionControl"
  enable-gtm-status = true
[[layers]]
  name = "lang#elixir"
[[layers]]
  name = "lang#vue"
[[layers]]
  name = "github"
[[layers]]
  name = "git"
[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 40
[[layers]]
  name = "edit"
[[layers]]
  name = "colorscheme"
[[layers]]
  name = "tools"
[[layers]]
  name = "lang#scala"
[[layers]]
  name = "lang#swift"
[[layers]]
  name = "lang#sh"
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "tmux"
[[layers]]
  name = "lang#rust"
  recommended-style = true
[[layers]]
  name = "lang#vim"
[[layers]]
  name = "lang#java"
[[layers]]
  name = "lang#dart"
[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "dart",
    "elixir",
    "scala",
    "go",
    "dockerfile"
  ]
  [layers.override_cmd]
   elixir = ["/Users/pedromangabeira/.vscode/extensions/jakebecker.elixir-ls-0.2.25/elixir-ls-release/language_server.sh"]
[[layers]]
  name = "checkers"
[[layers]]
  name = "lang#go"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "sudo"
[[layers]]
  name = "incsearch"
[[layers]]
  name = "indentmove"
[[layers]]
  name = "tags"
[[layers]]
  name = "exprfold"
