[[custom_plugins]]
name = 'moll/vim-bbye'
merged = 0

[[custom_plugins]]
name = 'chriskempson/base16-vim'
merged = 0

[[custom_plugins]]
name = 'vim-airline/vim-airline'
merged = 0

[[custom_plugins]]
name = 'vim-airline/vim-airline-themes'
merged = 0

[[custom_plugins]]
name = 'tpope/vim-cucumber'
merged = 0

[[custom_plugins]]
name = 'sodapopcan/vim-twiggy'
merged = 0

[[custom_plugins]]
name = 'toml-lang/toml'
merged = 0

[[custom_plugins]]
name = 'kristijanhusak/vim-carbon-now-sh'
merge = 0

[[custom_plugins]]
name = 'vim-scripts/dbext.vim'
merged = 0

[[custom_plugins]]
name = 'luochen1990/rainbow'
merge = 0

[[custom_plugins]]
name = 'ryanoasis/vim-devicons'
merge = 0

[[custom_plugins]]
name = 'christianrondeau/vim-base64'
merge = 0

[[custom_plugins]]
name = 'Shougo/vimproc.vim'
merge = 0

[[custom_plugins]]
name = 'whiteinge/diffconflicts'
merge = 0

[[custom_plugins]]
name = 'robertbasic/vim-hugo-helper'
merge = 0

[[custom_plugins]]
name = 'hashivim/vim-terraform'
merge = 0

[[custom_plugins]]
name = 'neoclide/coc.nvim'
merge = 0

[[custom_plugins]]
name = 'mg979/vim-visual-multi'
merge = 0

[[custom_plugins]]
name = 'tpope/vim-surround'
merge = 0

[[custom_plugins]]
name = 'satabin/hocon-vim'
merge = 0

[[custom_plugins]]
name = 'roxma/nvim-yarp'
merge = 0

[[custom_plugins]]
name = 'mattn/emmet-vim'
merge = 0

[[custom_plugins]]
name = 'vim-syntastic/syntastic'
merged = 0

[[custom_plugins]]
name = 'solarnz/thrift.vim'
merged = 0

[[layers]]
name = 'checkers'

[[layers]]
name = 'debug'

[[layers]]
name = 'denite'

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = 'complete'
auto_completion_tab-key_behavior = 'smart'

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'VersionControl'
enable-gtm-status = true

[[layers]]
name = 'github'

[[layers]]
name = 'git'
git-plugin = 'fugitive'

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 40

[[layers]]
name = 'edit'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'tools'

[[layers]]
name = 'tmux'

[[layers]]
name = 'lang#scala'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lsp'
filetypes = [
    'scala',
    'dockerfile',
]

[[layers]]
name = 'lang#toml'

name = 'lang#markdown'

[[layers]]
name = 'sudo'

[[layers]]
name = 'incsearch'

[[layers]]
name = 'indentmove'

[[layers]]
name = 'exprfold'

[[layers]]
name = 'checkers'
enable = false

[options]
colorscheme = 'base16-harmonic-dark'
colorscheme_bg = 'dark'
enable_guicolors = true
guifont = 'FuraCode Nerd Font:h14'
statusline_separator = 'nil'
statusline_inactive_separator = 'bar'
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_display_mode = true
lint_on_the_fly = true
filemanager = 'nerdtree'
autocomplete_method = 'coc'
filetree_direction = 'right'
enable_cursorcolumn = true
windows_smartclose = 'ยง'
statusline_left_sections = [
    'winnr',
    'major mode',
    'filename',
    'version control info',
    'search status',
]
statusline_right_sections = [
    'minor mode lighters',
    'syntax checking',
    'cursorpos',
    'percentage',
    'fileformat',
]
