[character]
use_symbol_for_status = true

[battery]
disabled = true

[git_commit]
disabled = false

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
untracked = '?${count}'
staged = '+${count}'
modified = '!${count}'
renamed = '»${count}'
conflicted = '=${count}'
deleted = '✘${count}'
